### ISSUE TITLE
IE issue: horizontal lines

### ISSUE THREAD

**Issue by kowalski90** [tbem/jquery.line#8]
The demo doesn't seem to work in IE. All the lines appear horizontally.

The same happens for the JSFiddle that I've found in another issue when testing in IE: http://jsfiddle.net/Fkj5X/

I've tested it in IE10. Works as it should in Firefox and Chrome.

**Comment by tbem** [comment]
I did a fix now, i tested it on a VM with IE11 it seems to be working now. 
Enjoy!
